### PR TITLE
Adding slice support for dynamic commands

### PR DESCRIPTION
**Pull request by crufter**
While added no tests for this, tested locally with the new version of the blog service:

```sh
$ micro posts --id=4 --title=hello --content="hi there" --tags=tag1 --tags=tag2 save
$ micro posts --id=5 --title=hello --content="hi there" --tags=tag1,tag2 save
$ micro posts query
{
	"posts": [
		{
			"id": "5",
			"title": "hello",
			"slug": "hello",
			"content": "hi there",
			"tags": [
				"tag1",
				"tag2"
			]
		},
		{
			"id": "4",
			"title": "hello",
			"slug": "hello",
			"content": "hi there",
			"tags": [
				"tag1",
				"tag2"
			]
		}
	]
}
```

### CODE REVIEW

**Review by ben-toogood — APPROVED** [review]

**Comment by ben-toogood** [comment]
It would be good to add a test for this. Maybe just adapt helloworld?

**Comment by crufter** [comment]
@ben I think I will create a separate service for it in my current blog PR, don't want to litter helloworld. Once I'm done with that PR will come back to this.

Also have to include this in the reference.

**Comment by asim** [comment]
I think a test for the parser makes sense. It doesn't have to be a service. Literally test the function with the expected inputs and outputs.

**Comment by crufter** [comment]
@asim true that!

**Comment by crufter** [comment]
Added unit tests

**Pull request merged**
