### PR TITLE
change the output of micro stats

### PR DESCRIPTION
**Pull request by lambdaR**
change the output of `micro stats service_name` to :    

```
service         users
----------------------------------------------------------
version         latest
node            users-8793a1b3-90f9-404c-89e6-9df459c02db3
address:port    172.17.0.2:45787
started         Nov 22 17:13:04
uptime          23s
memory          1.43mb
threads         20
gc              123.531µs
----------------------------------------------------------
version         latest
node            users-5624a1b3-404c-90f9-89e6-9df459c02fs5
address:port    172.17.0.2:45787
started         Nov 22 17:13:04
uptime          23s
memory          1.43mb
threads         20
gc              123.531µs
----------------------------------------------------------
version         v0.2.1
node            users-61135r5t2-90f9-404c-89e6-59c09df42db3
address:port    172.17.0.2:45787
started         Nov 22 17:13:04
uptime          23s
memory          1.43mb
threads         20
gc              123.531µs

```

### CODE REVIEW

**Comment by asim** [comment]
why?

**Comment by lambdaR** [comment]
current out: 
```
service  users

version latest

node            address:port            started uptime  memory  threads gc
users-4b2e2dc0-071a-4c0e-a6a3-c9e19b6fe1fd              172.17.0.2:44025                Nov 22 20:58:32 16s     1.54mb  20      94.278µs
```

**Comment by lambdaR** [comment]
fields are not aligned with values and the line where values are displayed a bit long

**Comment by asim** [comment]
surely the simpler solution is tabwriter and shorter uuids?

**Pull request closed without merging**
