### PR TITLE
fix(ci): goreleaser CGO enabled build release

### PR DESCRIPTION
**Pull request by alex-dna-tech**
## Manual test of `./micro server` execution

- [x] linux-amd64 ( Ubuntu x64 Intel PC)
- [x] linux-arm64 (Debian 11 Raspberry PI CM4)
- [x] linux-arm7 (Debian 11 Raspberry Pi Zero W2)
- [x] darwin-amd64 (MacOS Sonoma 14.4.1 MBP Intel)
- [x] windows-amd64 (Windows 10 VMWare)
- [x] windows-amd64 (Windows Server 2008 Intel PC)
- [x] windows-386 (Windows 7 VMWare)*1

---
*1 - binary executes but with runtime error
```
2024-04-24 07:05:57  file=server/server.go:134 level=error Failed to create runt
ime environment: exec: "micro.exe": cannot run executable found relative to curr
ent directory
```

### CODE REVIEW

**Comment by asim** [comment]
Let me know when you want it merged.

**Comment by alex-dna-tech** [comment]
I have tested releaser on my repo.
I do not have the opportunity to test on these platforms:
- darwin-arm64 (M1 or M2)
- windows-arm64 ()

We can rely on [gorelease-cross supported list](https://github.com/goreleaser/goreleaser-cross?tab=readme-ov-file#supported-toolchainsplatforms).

You can merge.

**Comment by alex-dna-tech** [comment]
BTW goreleaser supports docker build. So we can refactor the docker image release stage. 

Some scripts do same things:
- .github/workflows/docker.yml
- .github/workflows/hub.yml
- scripts/build_all_platforms.sh

**Comment by asim** [comment]
Looks good, thanks Alex. 4.6.0 is out using the new CGO enabled goreleaser

**Pull request merged**
