### PR TITLE
fix usage for argument --server_name / MICRO_SERVER_NAME variable

### PR DESCRIPTION
**Pull request by GJRTimmer**
#86

### CODE REVIEW

**Comment by asim** [comment]
Please change ServerName to Name and then I will merge.

**Comment by GJRTimmer** [comment]
@asim Done.

@asim Is this maybe something we should do throughout the entire micro environment ?

**Comment by asim** [comment]
The build has failed. This cannot be merged yet. Please fix. https://travis-ci.org/micro/micro/builds/198005246

What do you mean "something we should do throughout the entire micro environment"?

**Comment by GJRTimmer** [comment]
@asim Missed one rename, repushed with rebase.

Maybe this is something not unique to only the micro/micro project.

I'm research these awesome repositories to use them within a company project, so far I'm researching the possibilities about hardcoded namespace(s) service name(s) versus custom overrides like ```go.micro.srv.event.*```

So please don't feel offended if I'm creating several PR's over the next few weeks which addresses things like this PR.

Overall this is really an awesome ecosystem.

**Comment by asim** [comment]
The naming issue is only related to micro/micro because it does not call service.Init to parse command line flags. Any regular service you see throughout the repo does not have this issue.

**Comment by GJRTimmer** [comment]
Hardcoded values like https://github.com/micro/event-srv/blob/master/event/event.go#L29

**Comment by asim** [comment]
Yea in those cases it may make sense. Thanks for the contribution.

**Comment by GJRTimmer** [comment]
Can we somehow pass a the current name within the context so we can use a simple ```fmt.Sprintf``` for the error messages ?

**Comment by asim** [comment]
Join the slack if you want to discuss things rather than in issues or PRs http://slack.micro.mu

**Pull request merged**
