### PR TITLE
Added Service and Method Selection Dropdown in the query page of Web

### PR DESCRIPTION
**Pull request by swarvanusg**
Hi, 

I'm new to the micro project, and its community. Its my first pull request.

I have changed the query page. I have added Selection from Dropdown option for service and its methods. The service dropdown list is populated by all available service, where the method list is populated based on what service is currently selected.

1> At First the screen looks like:

no selection

2> The drop down list of services:

serviceselection

3> The drop down list of methods for a specific service:

methodselection

4> If a service has no methods it gets a black list:

servicewithnomethod

5>  Now use a service with ease. No need to type.

useservice

The reason the output is different from the expected is the same of issue #25 
It has nothing to do with the current changes. 

Please suggest if any change required. 

Thanks 
- Swarvanu

### CODE REVIEW

**Comment by asim** [comment]
Thanks for the PR. I like the look of it. Only nitpick. I want the ability to query anything behind the API even if its not registered. There's a notion of internal handlers that are not advertised to the registry. Would it be possible to flip between select list and input?

**Comment by swarvanusg** [comment]
Yes sure. In that case we can make the service as a select list, but for the method we could have both the option. I'll work on that and update the PR accordingly.

**Comment by asim** [comment]
It would be good to be able to query services that are not registered. That seems like a bizarre idea but something in practice that is quite possible.

**Comment by swarvanusg** [comment]
Thank you @asim . I think API which are not registered (or hidden) could be useful for service default operations e.g. Metric collection, log collection, or some platform specific implementation maybe for monitoring or governing the services

**Comment by asim** [comment]
Having given it more thought. Lets take it as is and if anyone complains we can change later. Only nitpicks now. Please use camelCase rather than underscores for variable and make the serviceMap `map[string][]*registry.Endpoint` rather than using interface for key and deferencing the endpoint.

**Comment by swarvanusg** [comment]
Updated the PR as per the discussion. And tested with the latest changes (issue #25 Fix). 

latestcommits

**Comment by swarvanusg** [comment]
Hi @asim ,

Added Other Method Selection Option, for Unregistered Method Support, in case we need it in future. 
So below are the descriptions:

1> While no service and Method is selected the screen looks like:

noselection


2> Now we have an option to select "- Other" that will allow us to specify any method:

theotherselectionoption


3> While "- Other" option is not selected the "Other Method" input field is disabled:

disabledfeild


4> Example of execution of a Method Specified in the "Other Method" section:

othermethodexecution


5> Care is taken to reset and disable the "Other Method" section while we change service or method:

changeservice

please suggest if any farther changes are required

Thanks,
Swarvanu

**Comment by asim** [comment]
Ok looks good.

**Pull request merged**
