### PR TITLE
Installing from source not working

### PR DESCRIPTION
**Pull request by a0v0**
## Pull Request template
Please, go through these steps before clicking submit on this PR.

1. Give a descriptive title to your PR.
2. Provide a description of your changes.
3. Make sure you have some relevant tests.
4. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if applicable).

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

### CODE REVIEW

**Comment by asim** [comment]
Can you explain what the error is rather than just commenting it out?

**Comment by a0v0** [comment]
image
@asim  take a look

**Comment by asim** [comment]
Ok so we just need /v3 at the end

**Comment by a0v0** [comment]
when appending /v3 at end and using @latest tag then micro version v3.5.0 is getting installed. I have checked both in windows and linux os

**Comment by asim** [comment]
Version has to be manually bumped in cmd/version.go. I've done that, retagged and updated the readme.

**Pull request closed without merging**
