### PR TITLE
change command 'new' instructions

### PR DESCRIPTION
**Pull request by opriz**
#836 Change `protoc` install instructions.

### CODE REVIEW

**Comment by asim** [comment]
Is bytedance using micro?

**Comment by opriz** [comment]
Not really. Just out of my own interest. 😄
There are always stumbling blocks left over from history, you know.

**Comment by opriz** [comment]
@asim 
Could you please revert this change? 
I only represent myself, not the company. I changed git config, but didn't notice here is a "Co-author". 
Thanks, or I might got in trouble. 😕

**Comment by asim** [comment]
Its a completely free open source project. Do not worry about it.

**Pull request merged**
