### PR TITLE
micro config

### PR DESCRIPTION
**Pull request by printfcoder**
depends on: https://github.com/micro/go-micro/pull/1118

supports:  etcd, memory, roach.

k-v store and based on: go-micro/store.

interfaces:
- Read
- Create
- Update
- Delete
- Watch

## web dashboard
   in next version

### CODE REVIEW

**Comment by asim** [comment]
In a mergeable state?

**Comment by printfcoder** [comment]
yea, but go-micro/store/crokcoach needs to support connection url like `postgre://***`, i will enhance this.

**Comment by asim** [comment]
I've made an update to the go-micro/config source to move from `service Service` to `service Config` so there will need to be an update here. 

https://github.com/micro/go-micro/commit/1c19678d04181658118155030ba67306319565fa

**Comment by printfcoder** [comment]
@asim its done.

**Comment by asim** [comment]
Thanks. Let me know when this is in a place to merge.

**Comment by printfcoder** [comment]
@asim I think it can be merged. we need support  UI-admin, version control, rollback in future versions. I will continue working on this.

**Pull request merged**
