### PR TITLE
Add @crufter's model

### PR DESCRIPTION
**Pull request by asim**
Merging @crufter's work on the model. Includes changes from this PR to the interface https://github.com/micro/dev/pull/11. Will continue to evolve from here and potentially include further future models like sql, graph, cache, etc.

### CODE REVIEW

**Comment by crazybber** [comment]
this is quite cool

**Comment by crazybber** [comment]
i think if we can add grpc reflection ablity into server end to  support some case ,such as grpcui(like postman  but for grpc.)

**Comment by asim** [comment]
> this is quite cool
> 
> i think if we can add grpc reflection ablity into server end to support some case ,such as grpcui(like postman but for grpc.) with enviroment flag support ,such as a debug mode.

If we change the way in which we register handlers then thats possible. Right now its difficult because we have our own custom grpc server implementation.

**Comment by crazybber** [comment]
> > this is quite cool
> > i think if we can add grpc reflection ablity into server end to support some case ,such as grpcui(like postman but for grpc.) with enviroment flag support ,such as a debug mode.
> 
> If we change the way in which we register handlers then thats possible. Right now its difficult because we have our own custom grpc server implementation.

use a static router to by pass 3rd register ability ,just provide direct gprc service call by name plus with grpcui/postman ,which is quite useful and efficiency in development enviroment  for developing.

**Pull request merged**
