### PR TITLE
Fix: Gitlab private repository deployment

### PR DESCRIPTION
**Pull request by a0v0**
the url generated checkoutGitLabPrivate function is ok but getting gzip: invalid header error 
can someone take a look @asim

### CODE REVIEW

**Comment by a0v0** [comment]
@asim can you take a look

**Comment by asim** [comment]
Have you tested it?

**Comment by a0v0** [comment]
Yes. But try it for yourself to make sure everything is well and good.

**Comment by asim** [comment]
I'm not a user of gitlab so it doesn't matter much to me

**Pull request merged**
